// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using intprogödev.Models.Data;

#nullable disable

namespace intprogödev.Migrations
{
    [DbContext(typeof(OgrenciDbContext))]
    partial class OgrenciDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciOgrenciDers", b =>
                {
                    b.Property<int>("OgrenciDerslerId")
                        .HasColumnType("int");

                    b.Property<int>("OgrencilerId")
                        .HasColumnType("int");

                    b.HasKey("OgrenciDerslerId", "OgrencilerId");

                    b.HasIndex("OgrencilerId");

                    b.ToTable("OgrenciOgrenciDers");
                });

            modelBuilder.Entity("intprogödev.Models.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Kredi")
                        .HasColumnType("tinyint");

                    b.Property<int?>("OgrenciDersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciDersId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("intprogödev.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numara")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("intprogödev.Models.OgrenciDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OgrenciDersler");
                });

            modelBuilder.Entity("OgrenciOgrenciDers", b =>
                {
                    b.HasOne("intprogödev.Models.OgrenciDers", null)
                        .WithMany()
                        .HasForeignKey("OgrenciDerslerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("intprogödev.Models.Ogrenci", null)
                        .WithMany()
                        .HasForeignKey("OgrencilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("intprogödev.Models.Ders", b =>
                {
                    b.HasOne("intprogödev.Models.OgrenciDers", null)
                        .WithMany("Dersler")
                        .HasForeignKey("OgrenciDersId");
                });

            modelBuilder.Entity("intprogödev.Models.OgrenciDers", b =>
                {
                    b.Navigation("Dersler");
                });
#pragma warning restore 612, 618
        }
    }
}
